---
- name: Setup Flask app on webservers
  hosts: webservers
  become: yes
  tasks:
    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
        update_cache: yes

    - name: Install Flask
      pip:
        name: flask

    - name: Copy Flask app
      copy:
        src: application2.py
        dest: /home/ubuntu/application2.py
        mode: '0755'

    - name: Setup systemd service for flask app
      copy:
        dest: /etc/systemd/system/flaskapp.service
        content: |
          [Unit]
          Description=Flask App
          After=network.target

          [Service]
          ExecStart=/usr/bin/python3 /home/ubuntu/application2.py
          Restart=always
          User=ubuntu

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start flaskapp service
      systemd:
        name: flaskapp
        enabled: yes
        state: started

    - name: Install SNMPD
      apt:
        name: snmpd
        update_cache: yes

    - name: Deploy SNMPD config
      copy:
        src: snmpd.conf
        dest: /etc/snmp/snmpd.conf
        mode: '0644'

    - name: Restart SNMPD
      systemd:
        name: snmpd
        state: restarted
        enabled: yes

- name: Setup HAproxy load balancer
  hosts: HAproxy
  become: yes
  tasks:
    - name: Install HAproxy
      apt:
        name: haproxy
        update_cache: yes

    - name: Deploy HAproxy config
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'

    - name: Restart HAproxy
      systemd:
        name: haproxy
        state: restarted
        enabled: yes

    - name: Install nginx for UDP load balancing
      apt:
        name: nginx
        update_cache: yes

    - name: Configure nginx for UDP SNMP
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes


