---
- name: Configure all nodes
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

- name: Set up Flask Web Servers
  hosts: webservers
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - snmpd
        state: present

    - name: Install Flask using pip
      pip:
        name: flask
        executable: pip3

    - name: Install Gunicorn using pip
      pip:
        name: gunicorn
        executable: pip3

    - name: Copy Flask app to server
      copy:
        src: application2.py
        dest: /home/ubuntu/application2.py
        mode: '0755'

    - name: Launch Flask app with Gunicorn
      shell: gunicorn -w 2 -D -b 0.0.0.0:80 application2:app
      args:
        chdir: /home/ubuntu

    - name: Configure SNMP daemon
      template:
        src: snmpd.conf.j2
        dest: /etc/snmp/snmpd.conf

    - name: Restart SNMPD
      service:
        name: snmpd
        state: restarted

- name: Configure HAProxy + NGINX Host
  hosts: HAproxy
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - haproxy
          - nginx
          - snmp
          - snmp-mibs-downloader
        state: present      

    - name: Deploy HAProxy config
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      
    - name: Deploy NGINX config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted
        
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

