---
- name: Setup Base Config on All Hosts
  hosts: all
  gather_facts: yes

- name: Configure Web Servers
  hosts: webservers
  become: yes
  vars:
    flask_app_path: /home/ubuntu/application2.py
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python, pip, venv
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Install Flask via pip
      pip:
        name: flask
        executable: pip3

    - name: Install Gunicorn
      apt:
        name: gunicorn
        state: present

    - name: Deploy Flask application
      copy:
        src: application2.py
        dest: "{{ flask_app_path }}"
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Create systemd service for Flask app with Gunicorn
      copy:
        dest: /etc/systemd/system/flaskapp.service
        content: |
          [Unit]
          Description=Gunicorn instance to serve Flask app
          After=network.target

          [Service]
          User=ubuntu
          Group=www-data
          WorkingDirectory=/home/ubuntu
          ExecStart=/usr/bin/gunicorn --workers 2 --bind 0.0.0.0:80 application2:app

          [Install]
          WantedBy=multi-user.target
      notify: restart flaskapp

    - name: Enable and start flaskapp service
      systemd:
        name: flaskapp
        enabled: yes
        state: started

    - name: Install SNMP daemon
      apt:
        name: snmpd
        state: present

    - name: Configure SNMP daemon
      template:
        src: snmpd.conf.j2
        dest: /etc/snmp/snmpd.conf
      notify: restart snmpd

  handlers:
    - name: restart flaskapp
      systemd:
        name: flaskapp
        state: restarted

    - name: restart snmpd
      service:
        name: snmpd
        state: restarted

- name: Configure HAProxy Host
  hosts: HAproxy
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install HAProxy
      apt:
        name: haproxy
        state: present

    - name: Install Nginx and SNMP tools
      apt:
        name:
          - nginx
          - snmp
          - snmp-mibs-downloader
        state: present

    - name: Deploy HAProxy config
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: restart haproxy

    - name: Deploy Nginx config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: restart nginx

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted

    - name: restart nginx
      service:
        name: nginx
        state: restarted

