---
- hosts: all
  gather_facts: true

- hosts: webservers
  become: true
  become_method: sudo
  gather_facts: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: Install python3, pip3
      apt:
        name:
          - python3
          - python3-pip
        update_cache: yes

    - name: Install flask
      pip:
        executable: pip3
        name: flask
        state: latest

    - name: Install gunicorn
      apt:
        name: gunicorn

    - name: Copy Flask app to remote server
      copy:
        src: application2.py
        dest: /home/ubuntu/application2.py
        owner: ubuntu
        mode: "0644"

    - name: Run Flask application with Gunicorn in background
      shell: gunicorn -w 2 -D -b 0.0.0.0:80 application2:app
      args:
        chdir: /home/ubuntu

    - name: Copy UDP app to remote server
      copy:
        src: udp_app.py
        dest: /home/ubuntu/udp_app.py
        owner: ubuntu
        mode: "0755"

    - name: Run UDP application in background
      shell: nohup python3 /home/ubuntu/udp_app.py &
      args:
        executable: /bin/bash

- hosts: HAproxy
  become: true
  become_method: sudo
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: latest

    - name: Configure HAProxy with TCP & UDP
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        validate: haproxy -c -f %s
      notify: restart haproxy

    - name: Verify HAProxy configuration
      command: haproxy -c -f /etc/haproxy/haproxy.cfg
      register: haproxy_validate
      changed_when: false

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted

